/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.LocationRole;

import userinterface.InfraRole.*;
import Business.EcoSystem;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Saivignesh Sridhar
 */
public class LocationOrgInfoJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewUpdateRestJPanel
     */
    private final JPanel container;
    private final EcoSystem system;
   
    public LocationOrgInfoJPanel(JPanel container, UserAccount account, EcoSystem system) {
        initComponents();
         this.container = container;
         this.system = system;
         
         lblTitle.setText(account.getUsername()+ "'s Details");
         txtLocName.setText(account.getName());
         txtLocContact.setText(account.getPhone());
         txtLocEmail.setText(account.getEmail());
         
         txtLocName.setEnabled(false);
        disableEdit();
        
    }
private void disableEdit(){
    txtLocName.setEditable(false);
    txtLocContact.setEditable(false);
    
    txtLocEmail.setEditable(false);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        txtLocEmail = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtLocName = new javax.swing.JTextField();
        lblContact = new javax.swing.JLabel();
        lblLocName = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        txtLocContact = new javax.swing.JTextField();
        btnEnableUpdate = new javax.swing.JButton();
        btnSaveChanges = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));
        setForeground(new java.awt.Color(0, 51, 51));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtLocEmail.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        txtLocEmail.setForeground(new java.awt.Color(0, 51, 51));
        add(txtLocEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 127, -1));

        lblEmail.setBackground(new java.awt.Color(204, 255, 255));
        lblEmail.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(0, 51, 51));
        lblEmail.setText(" Email ID :");
        add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, -1, -1));

        txtLocName.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        txtLocName.setForeground(new java.awt.Color(0, 51, 51));
        add(txtLocName, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 127, -1));

        lblContact.setBackground(new java.awt.Color(204, 255, 255));
        lblContact.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        lblContact.setForeground(new java.awt.Color(0, 51, 51));
        lblContact.setText("Contact No :");
        add(lblContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, -1));

        lblLocName.setBackground(new java.awt.Color(204, 255, 255));
        lblLocName.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        lblLocName.setForeground(new java.awt.Color(0, 51, 51));
        lblLocName.setText("Location Name :");
        add(lblLocName, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 124, -1, -1));

        lblTitle.setBackground(new java.awt.Color(204, 255, 255));
        lblTitle.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(0, 51, 51));
        lblTitle.setText("Organization Details");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 33, -1, -1));

        txtLocContact.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        txtLocContact.setForeground(new java.awt.Color(0, 51, 51));
        add(txtLocContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 127, -1));

        btnEnableUpdate.setBackground(new java.awt.Color(204, 255, 255));
        btnEnableUpdate.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        btnEnableUpdate.setForeground(new java.awt.Color(0, 51, 51));
        btnEnableUpdate.setText("Enable Update");
        btnEnableUpdate.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEnableUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnableUpdateActionPerformed(evt);
            }
        });
        add(btnEnableUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 354, 106, -1));

        btnSaveChanges.setBackground(new java.awt.Color(204, 255, 255));
        btnSaveChanges.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        btnSaveChanges.setForeground(new java.awt.Color(0, 51, 51));
        btnSaveChanges.setText("Save Changes");
        btnSaveChanges.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSaveChanges.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveChangesActionPerformed(evt);
            }
        });
        add(btnSaveChanges, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 383, 106, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnableUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnableUpdateActionPerformed
        // TODO add your handling code here:
       
        txtLocContact.setEditable(true);
        txtLocEmail.setEditable(true);
      
        txtLocName.setEditable(true);
        
        btnEnableUpdate.setEnabled(false);
    }//GEN-LAST:event_btnEnableUpdateActionPerformed

    private void btnSaveChangesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveChangesActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnSaveChangesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnableUpdate;
    private javax.swing.JButton btnSaveChanges;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblContact;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblLocName;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtLocContact;
    private javax.swing.JTextField txtLocEmail;
    private javax.swing.JTextField txtLocName;
    // End of variables declaration//GEN-END:variables
}
