

package userinterface.MusicianRole;


import userinterface.InfraRole.*;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.Entertainment.MusicianDirectory;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author  Saivignesh Sridhar
 */
public class MusicWorkAreaJPanel extends javax.swing.JPanel {
    
    private final JPanel userProcessContainer;
    private final EcoSystem system;
    private final UserAccount userAccount;
    private final Organization organization;
    private final Network network;
    private final Enterprise enterprise;
    private final MusicianDirectory musicianDirectory;
    
    /** Creates new form AdminWorkAreaJPanel */
    public MusicWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization org, Enterprise ent, Network net, EcoSystem system,MusicianDirectory musicianDirectory) {
        initComponents();
        lblRestName.setText(account.getUsername());
        lblRestAdmin.setText(account.getEmployee().getName()+" 's Admin Page");
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.userAccount = account;
        this.organization = org;
        this.enterprise = ent;
        this.network = net;
        this.musicianDirectory = musicianDirectory;

      
        //valueLabel.setText();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRestAdmin = new javax.swing.JLabel();
        btnRestInfo = new javax.swing.JButton();
        btnmanagemusicians = new javax.swing.JButton();
        btnmanagerequests = new javax.swing.JButton();
        lblRestName = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));
        setForeground(new java.awt.Color(0, 51, 51));
        setToolTipText("");
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblRestAdmin.setBackground(new java.awt.Color(204, 255, 255));
        lblRestAdmin.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        lblRestAdmin.setForeground(new java.awt.Color(0, 51, 51));
        lblRestAdmin.setText("Music  Administration Page");
        add(lblRestAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        btnRestInfo.setBackground(new java.awt.Color(204, 255, 255));
        btnRestInfo.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        btnRestInfo.setForeground(new java.awt.Color(0, 51, 51));
        btnRestInfo.setText("Manage Musician Info");
        btnRestInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestInfoActionPerformed(evt);
            }
        });
        add(btnRestInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 210, -1));

        btnmanagemusicians.setBackground(new java.awt.Color(204, 255, 255));
        btnmanagemusicians.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        btnmanagemusicians.setForeground(new java.awt.Color(0, 51, 51));
        btnmanagemusicians.setText("Manage Musicians");
        btnmanagemusicians.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmanagemusiciansActionPerformed(evt);
            }
        });
        add(btnmanagemusicians, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 210, -1));

        btnmanagerequests.setBackground(new java.awt.Color(204, 204, 255));
        btnmanagerequests.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        btnmanagerequests.setForeground(new java.awt.Color(0, 51, 51));
        btnmanagerequests.setText("Manage Requests");
        btnmanagerequests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmanagerequestsActionPerformed(evt);
            }
        });
        add(btnmanagerequests, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 210, -1));

        lblRestName.setBackground(new java.awt.Color(204, 255, 255));
        lblRestName.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        lblRestName.setForeground(new java.awt.Color(0, 51, 51));
        lblRestName.setText("Music Org Name");
        add(lblRestName, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 150, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnRestInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestInfoActionPerformed
        // TODO add your handling code here:
    
    }//GEN-LAST:event_btnRestInfoActionPerformed

    private void btnmanagemusiciansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmanagemusiciansActionPerformed
        MusicEquipJPanel managemusiciansInfoJPanel = new MusicEquipJPanel(userProcessContainer,userAccount,EcoSystem.getInstance(),musicianDirectory);
        userProcessContainer.add("MusicEquipJPanel", managemusiciansInfoJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);   
    
    }//GEN-LAST:event_btnmanagemusiciansActionPerformed

    private void btnmanagerequestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmanagerequestsActionPerformed
        MusicRequestJPanel managemusicrequestInfoJPanel = new MusicRequestJPanel(userProcessContainer,userAccount,EcoSystem.getInstance());
        userProcessContainer.add("MusicRequestJPanel", managemusicrequestInfoJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnmanagerequestsActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRestInfo;
    private javax.swing.JButton btnmanagemusicians;
    private javax.swing.JButton btnmanagerequests;
    private javax.swing.JLabel lblRestAdmin;
    private javax.swing.JLabel lblRestName;
    // End of variables declaration//GEN-END:variables
    
}
