package userinterface.GovtAuthRole;


import userinterface.LocationRole.*;
import userinterface.InfraRole.*;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.HostGovtWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author  Saivignesh Sridhar
 */
public class SecurityERWorkAreaJPanel extends javax.swing.JPanel {
    
    private final JPanel userProcessContainer;
    private final EcoSystem system;
    private final UserAccount userAccount;
    private final Organization organization;
    private final Network network;
    private final Enterprise enterprise;
    
    /** Creates new form AdminWorkAreaJPanel */
    public SecurityERWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization org, Enterprise ent, Network net, EcoSystem system) {
        initComponents();
        lblRestName.setText(account.getUsername());
        lblRestAdmin.setText(account.getEmployee().getName()+" 's Admin Page");
          this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.userAccount = account;
        this.organization = org;
        this.enterprise = ent;
        this.network = net;
        populateTable();
      
        //valueLabel.setText();
    }
    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblEventAuth.getModel();

        model.setRowCount(0);
        for (WorkRequest request : userAccount.getWorkQueue().getWorkRequestList()) {
            if (request instanceof HostGovtWorkRequest) {
          //  if (request.getStatus().equals("Awaiting Govt Approval")) {
                Object[] row = new Object[8];
                row[0] = request;
                row[1] = ((HostGovtWorkRequest) request).getEventName();
                row[2] = ((HostGovtWorkRequest) request).getEvenCat();
                row[3] = request.getStatus();
                row[4] = request.getSender();
                row[5] = ((HostGovtWorkRequest) request).getAttendance();
                row[6] = ((HostGovtWorkRequest) request).getPlannedDate();
                row[7] = request.getMessage();

                model.addRow(row);
            //}
            }
        }
    }
    private void disableFields(){
    txtAddMsg.setText("");
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRestAdmin = new javax.swing.JLabel();
        lblRestName = new javax.swing.JLabel();
        scrollOrderList = new javax.swing.JScrollPane();
        tblEventAuth = new javax.swing.JTable();
        btnApprove = new javax.swing.JButton();
        btnReject = new javax.swing.JButton();
        blAddMessage = new javax.swing.JLabel();
        txtAddMsg = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 204, 255));
        setForeground(new java.awt.Color(0, 51, 51));
        setToolTipText("");
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblRestAdmin.setBackground(new java.awt.Color(204, 255, 255));
        lblRestAdmin.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        lblRestAdmin.setForeground(new java.awt.Color(0, 51, 51));
        lblRestAdmin.setText("Event Authorization Area");
        add(lblRestAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, -1, -1));

        lblRestName.setBackground(new java.awt.Color(204, 255, 255));
        lblRestName.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        lblRestName.setForeground(new java.awt.Color(0, 51, 51));
        lblRestName.setText("Govt Official Name");
        add(lblRestName, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 180, 30));

        tblEventAuth.setBackground(new java.awt.Color(204, 204, 255));
        tblEventAuth.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        tblEventAuth.setForeground(new java.awt.Color(0, 51, 51));
        tblEventAuth.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Request ID", "Event Name", "Event Category", "Status", "Host Name", "Attendance", "Planned Date", "Message"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollOrderList.setViewportView(tblEventAuth);

        add(scrollOrderList, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 780, 110));

        btnApprove.setBackground(new java.awt.Color(204, 255, 255));
        btnApprove.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        btnApprove.setForeground(new java.awt.Color(0, 51, 51));
        btnApprove.setText("Approve Request");
        btnApprove.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnApprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApproveActionPerformed(evt);
            }
        });
        add(btnApprove, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 130, 30));

        btnReject.setBackground(new java.awt.Color(204, 255, 255));
        btnReject.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        btnReject.setForeground(new java.awt.Color(0, 51, 51));
        btnReject.setText("Reject Request");
        btnReject.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnReject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRejectActionPerformed(evt);
            }
        });
        add(btnReject, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 360, 130, 30));

        blAddMessage.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        blAddMessage.setForeground(new java.awt.Color(41, 50, 80));
        blAddMessage.setText("Additional Message:");
        add(blAddMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, -1, -1));

        txtAddMsg.setBackground(new java.awt.Color(204, 204, 255));
        add(txtAddMsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 300, 200, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnApproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApproveActionPerformed
        // TODO add your handling code here: 
 
        int selectedRow = tblEventAuth.getSelectedRow();
        if (selectedRow >= 0) {
            HostGovtWorkRequest request = (HostGovtWorkRequest) tblEventAuth.getValueAt(selectedRow, 0);
            String message = txtAddMsg.getText();
            if (message.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Kindly enter additional details to the Host.");
                return;
            }
            if (request.getStatus().equals("Awaiting Govt Approval")) {
            if (!"Event Authorized".equals(request.getStatus())) {
                request.setStatus("Event Authorized");
                request.setMessage(message);
                JOptionPane.showMessageDialog(null, "Event is Authorized!");
                    userAccount.setStatus("Available");
                populateTable();
                disableFields();
            } else {
                JOptionPane.showMessageDialog(null, "Event is already Authorized!");
            }
            } else {
                JOptionPane.showMessageDialog(null, "Select an appropriate Event!");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please select one row!");
        }
    }//GEN-LAST:event_btnApproveActionPerformed

    private void btnRejectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRejectActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblEventAuth.getSelectedRow();
        if (selectedRow >= 0) {
            HostGovtWorkRequest request = (HostGovtWorkRequest) tblEventAuth.getValueAt(selectedRow, 0);
            String message = txtAddMsg.getText();
            if (message.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Kindly enter the reason for Rejection");
                return;
            }
            if (!"Completed".equals(request.getStatus()) || !"In Progress".equals(request.getStatus())) {
                request.setStatus("Rejected");
                request.setMessage(message);
                JOptionPane.showMessageDialog(null, "Event Rejected!");
                    userAccount.setStatus("Available");
                populateTable();
            } else {
                JOptionPane.showMessageDialog(null, "Event is already " + request.getStatus());
            }
        } else {
            JOptionPane.showMessageDialog(null, "Kindly select a row.");
        }
    }//GEN-LAST:event_btnRejectActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel blAddMessage;
    private javax.swing.JButton btnApprove;
    private javax.swing.JButton btnReject;
    private javax.swing.JLabel lblRestAdmin;
    private javax.swing.JLabel lblRestName;
    private javax.swing.JScrollPane scrollOrderList;
    private javax.swing.JTable tblEventAuth;
    private javax.swing.JTextField txtAddMsg;
    // End of variables declaration//GEN-END:variables
    
}
