/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.HostRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Role.AuthRole;
import Business.Role.Role;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.HostGovtWorkRequest;
import Business.WorkQueue.WorkQueue;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Saivignesh Sridhar
 */
public class AddEventJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddEventJPanel
     */
    private final JPanel userProcessContainer;
    private final EcoSystem system;
    private final UserAccount userAccount;
    private final Organization organization;
    private final Network network;
    private final Enterprise enterprise;
    public AddEventJPanel(JPanel userProcessContainer, UserAccount account, Enterprise ent, EcoSystem system,  Network net, Organization org) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.userAccount = account;
        this.organization = org;
        this.enterprise = ent;
        this.network = net;
        
        state.setText(network.getName());
        lblIndoors.setText("Indoor Limit: "+network.getIgLimit());
        lblOutdoors.setText("Outdoor Limit: "+network.getOgLimit());
        cbEventCat.addItem("Indoor Event");
        cbEventCat.addItem("Outdoor Event");
    }
    private void disableFields(){
    txtEventName.setEnabled(false);
    dpEventDate.setEnabled(false);
    street.setEnabled(false);
    city.setEnabled(false);
    state.setEnabled(false);
    btnHost.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtEventName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        street = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        dpEventDate = new com.toedter.calendar.JDateChooser();
        city = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        state = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbEventCat = new javax.swing.JComboBox();
        slAttendance = new javax.swing.JSlider();
        lblAtt = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblIndoors = new javax.swing.JLabel();
        lblOutdoors = new javax.swing.JLabel();
        btnHost = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(25, 56, 82));
        jLabel1.setText("Host an Event");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Event Name");
        jLabel2.setToolTipText("");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, -1, -1));

        txtEventName.setToolTipText("");
        txtEventName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEventNameActionPerformed(evt);
            }
        });
        add(txtEventName, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, 393, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Planned Date");
        jLabel5.setToolTipText("");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, -1, -1));

        street.setToolTipText("");
        add(street, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 350, 393, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Street Address");
        jLabel11.setToolTipText("");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("City");
        jLabel12.setToolTipText("");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 390, -1, -1));

        dpEventDate.setToolTipText("");
        add(dpEventDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, 246, 26));

        city.setToolTipText("");
        add(city, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 390, 393, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("State");
        jLabel13.setToolTipText("");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 430, -1, -1));

        state.setEditable(false);
        state.setToolTipText("");
        state.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stateActionPerformed(evt);
            }
        });
        add(state, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 430, 393, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Event Category");
        jLabel3.setToolTipText("");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, -1, -1));

        cbEventCat.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        cbEventCat.setForeground(new java.awt.Color(25, 56, 82));
        cbEventCat.setToolTipText("");
        cbEventCat.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbEventCatItemStateChanged(evt);
            }
        });
        cbEventCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEventCatActionPerformed(evt);
            }
        });
        cbEventCat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cbEventCatKeyReleased(evt);
            }
        });
        add(cbEventCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, 230, -1));

        slAttendance.setBackground(new java.awt.Color(204, 204, 255));
        slAttendance.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        slAttendance.setForeground(new java.awt.Color(0, 102, 102));
        slAttendance.setMaximum(300);
        slAttendance.setMinimum(50);
        slAttendance.setPaintTicks(true);
        slAttendance.setToolTipText("");
        slAttendance.setValue(130);
        slAttendance.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slAttendanceStateChanged(evt);
            }
        });
        add(slAttendance, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 240, 133, 34));

        lblAtt.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        lblAtt.setForeground(new java.awt.Color(0, 102, 102));
        lblAtt.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblAtt.setToolTipText("");
        add(lblAtt, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, 74, 34));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Planned Attendance");
        jLabel6.setToolTipText("");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, -1, -1));

        lblIndoors.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblIndoors.setText("Indoor Limit XXX");
        lblIndoors.setToolTipText("");
        add(lblIndoors, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 220, -1, -1));

        lblOutdoors.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblOutdoors.setText("Outdoor Limit XXX");
        lblOutdoors.setToolTipText("");
        add(lblOutdoors, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 250, -1, -1));

        btnHost.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnHost.setForeground(new java.awt.Color(25, 56, 82));
        btnHost.setText("Host");
        btnHost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHostActionPerformed(evt);
            }
        });
        add(btnHost, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 480, 75, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtEventNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEventNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEventNameActionPerformed

    private void stateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stateActionPerformed

    private void cbEventCatItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbEventCatItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbEventCatItemStateChanged

    private void cbEventCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEventCatActionPerformed

    }//GEN-LAST:event_cbEventCatActionPerformed

    private void cbEventCatKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbEventCatKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_cbEventCatKeyReleased

    private void slAttendanceStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slAttendanceStateChanged
        // TODO add your handling code here:
        lblAtt.setText(String.valueOf(slAttendance.getValue())+"");
    }//GEN-LAST:event_slAttendanceStateChanged

    private void btnHostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHostActionPerformed
               
               Date eventDate = dpEventDate.getDate();
               Date sysDate = new Date();
               long diff = (eventDate.getTime() - sysDate.getTime())/(1000 * 60 * 60 * 24);
               System.out.println((int)diff);
        if (dpEventDate.getDate() == null || street.getText().isEmpty()
                || txtEventName.getText().isEmpty() || city.getText().isEmpty() ) {
            JOptionPane.showMessageDialog(null, "Kindly enter all the fields");
        }
        else if (diff < 0) {
                    JOptionPane.showMessageDialog(null, "Cannot enter a previous date");
        }
        else if (diff <=6) {
                    JOptionPane.showMessageDialog(null, "Cannot select a date within a week.");
        }
        else{           
        HostGovtWorkRequest hostgovtwr = new HostGovtWorkRequest();
        hostgovtwr.setRequestID();
        hostgovtwr.setStatus("Awaiting Govt Approval");
        hostgovtwr.setSender(userAccount);
        hostgovtwr.setAttendance(slAttendance.getValue());
        hostgovtwr.setMessage("Request sent to Govt");
        hostgovtwr.setEventName(txtEventName.getText());
        hostgovtwr.setEvenCat(String.valueOf(cbEventCat.getSelectedItem()));
        hostgovtwr.setPlannedDate(eventDate); 
        hostgovtwr.setLocNote(userAccount.getCity());
        hostgovtwr.setHost(userAccount);
        
        for (Network n : system.getNetworkList()) {
            for (Enterprise e : n.getEnterpriseDirectory().getEnterpriseList()) {
                for (Organization org : e.getOrganizationDirectory().getOrganizationList()) {
                    for (UserAccount ua : org.getUserAccountDirectory().getUserAccountList()) {
                        if (ua.getRole() instanceof AuthRole) {
                            ua.getWorkQueue().getWorkRequestList().add(hostgovtwr);
                            JOptionPane.showMessageDialog(null, "Request Sent Successfully!");
                            disableFields();
                        }
                    }
                }
            }   
        }
        
        
//        for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
//        for (UserAccount user : enterprise.getUserAccountDirectory().getUserAccountList()) {
//           if ( Enterprise.EnterpriseType.Government  == enterprise.getEnterpriseType()) {
//        user.getWorkQueue().getWorkRequestList().add(hostgovtwr);
//        JOptionPane.showMessageDialog(null, "Request Sent Successfully!");
//           }
//         }
//        }
        }
    }//GEN-LAST:event_btnHostActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHost;
    private javax.swing.JComboBox cbEventCat;
    private javax.swing.JTextField city;
    private com.toedter.calendar.JDateChooser dpEventDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblAtt;
    private javax.swing.JLabel lblIndoors;
    private javax.swing.JLabel lblOutdoors;
    private javax.swing.JSlider slAttendance;
    private javax.swing.JTextField state;
    private javax.swing.JTextField street;
    private javax.swing.JTextField txtEventName;
    // End of variables declaration//GEN-END:variables
}
